services:
  app:
    image: golang:latest
    container_name: go-fundamentos
    restart: on-failure
    tty: true
    build: .
    working_dir: /usr/src/app
    volumes:
      - go-fundamentos-volume:/usr/src/app/
volumes:
  go-fundamentos-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}
